---
    apiVersion: iofog.org/v1
    kind: Application
    metadata:
      name: natix-io
    spec:
      microservices:
       - name: Usage Anomaly Dashboard
         agent:
          name: local-agent
         config:
          tag: 'usage-anomaly-dashboard'
         images:
          x86: natix-io/usage-anomaly-dashboard:v1
          registry: local
         volumes: []
         ports: 
            - external: 7778
              internal: 7778
         env:
           - key: "PORT"
             value: "7778" 
           - key: "ANOMALY_REPORT_API"
             value: "http://192.168.1.5:5000/api/raw"        
       - name: Usage Anomaly Detector
         agent:
           name: local-agent
         config:
          tag: 'usage-anomaly-detector'
         images:
           x86: natix-io/usage-anomaly-detector:v1
           registry: local
         volumes: []
         ports: 
          - external: 5000
            internal: 5000
         env: []
       - name: Edge Device Cam1
         agent:
           name: local-agent
         config:
          tag: 'cam1'
          minUsage: 40
          maxUsage: 50
         images:
           x86: natix-io/edge-device:v1
           registry: local
         volumes: []
         ports: []
         env: []    
      routes:
          - from: Edge Device Cam1
            to: Usage Anomaly Detector
          - from: Usage Anomaly Detector
            to: Usage Anomaly Dashboard  
