---
apiVersion: iofog.org/v1
kind: Application
metadata:
  name: NATIX-io
spec:
  microservices:
   - name: Edge Device Cam1
     agent:
       name: local-agent
     config:
      tag: 'cam1'
      minUsage: 40
      maxUsage: 50
     images:
       x86: NATIX-io/edge-device:v1
       registry: local
     volumes: []
     ports: []
     env: []